# Generated by Django 3.0.5 on 2020-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='publicly',
            field=models.BooleanField(default=True, verbose_name='I agree that the link to my website can be publicly shown on main page of this web.'),
        ),
    ]
