# Generated by Django 3.0.3 on 2020-02-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Basic main page', 'verbose_name_plural': 'Basic main pages'},
        ),
    ]
